---
booktitle: Proceedings of the 2nd Machine Learning for Health symposium
shortname: ML4H
volume: '193'
year: '2022'
start: 2022-11-28
end: 2022-11-28
published: 2022-11-22
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: ML4H-2022
month: 0
cycles: false
bibtex_editor: Parziale, Antonio and Agrawal, Monica and Joshi, Shalmali and Chen,
  Irene Y. and Tang, Shengpu and Oala, Luis and Subbaswamy, Adarsh
editor:
- given: Antonio
  family: Parziale
- given: Monica
  family: Agrawal
- given: Shalmali
  family: Joshi
- given: Irene Y.
  family: Chen
- given: Shengpu
  family: Tang
- given: Luis
  family: Oala
- given: Adarsh
  family: Subbaswamy
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 2nd Machine Learning for Health symposium
    Held in New Orleans, Lousiana, USA & Virtual on 28 November 2022

  Published as Volume 193 by the Proceedings of Machine Learning Research on 22 November 2022.

  Volume Edited by:
    Antonio Parziale
    Monica Agrawal
    Shalmali Joshi
    Irene Y. Chen
    Shengpu Tang
    Luis Oala
    Adarsh Subbaswamy

  Series Editors:
    Neil D. Lawrence
date_str: 28 Nov
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v193"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v193
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v193
email: ''
conference:
  name: Machine Learning for Health
  url: https://ml4health.github.io/2022/
  location: New Orleans, Lousiana, USA & Virtual
  dates:
  - 2022-11-28
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v193/ml4h22.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v193/ml4h22.bib
